[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "78bc6fc2006417ab5e7a8e2bba8a3bf72e3f62ad"
libgfortran_version = "5.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "cdaaca5b2657724586562d1113beb2e1ed5d0f4337761bdcc58bedf56747c71a"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "694245115963ded63cc5cca2d72e64273947d265"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "69e95d0a8e5c20762c9ea3c1c114f238d68780d01d2a57c4af57302946d1028c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "c53807eb78fb31a76749c1bf6a64539500e7dc2c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "9905377258ea7493702419e478fee1bbbb149e9a0529de3929ed30ac4c07128c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "0c2c564d76406a9e9c84377cfee5b3ce96aea66e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "9667a1b0f040540375501963d4b531654465095f978d32c7671520334ff495df"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "758507d2b51dd3a71db42dcb323cb9d87323c1ef"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "ca49d9331222b21cb9264b9986ec0c35f08ba385cddcb2c954c210d9acbd7ef2"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "6f0224b6afeb4a4061a5b61e98410b055882ba9b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "2fb0a8ad47aa614afc1205216943a6a4fd471008c0b6a264b121610be4603483"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "6bb3117ac3a1c4b17c433a004c319d357f39b609"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "5aaf5337614c60c04a336b6cfe7051dbf5a8482816f22348d97e6d3fa7158fd3"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "33070c92e1b9e96b914ec494c557323c840e6257"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "cabc3ddc09720ebaaeb3b524646114e4799be2d38c4b827118ffe40977e0eff3"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5920f434fb96f17672fda1b9e21a272d6f62a017"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "dc893909508f3285a4df2b9e54a5dad24f647fdf42ceed66da89c6be8e931e24"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d538bac4d016044d33a52fe1d88a36f2f0793448"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "815289d432c3669f4f6888e7cc9bdaa188b04ee2bc856c70c5a1422d6ccdcd19"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "212da57c0d65b5563df4ea1458180fb60d00abd0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "f4b14101f323929c167a9bd8df75b122f4e8a246080b6306314e18b4f41addb8"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ecfe9e92c4b7e755fb6dc384fd40091191e5199"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "331672beeab79069db19fe2976636be41617c8f4189e312549a2bb0181bb6ba7"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "27221d08825bb91c0fb9ec0883caa1a1b2e21ed7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "2dc5da5a8f8073f193e5804e57a82d2f2732ebb859ff05ea5a19fa7934fc26a7"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "647a17325657527190bb4c1011327e8e8bed39b1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "0a67c81f8a0cfb891a931375a976992524814f2ee265e297ba79c29f7c6fc281"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "86696d434f9ed99e9eba4384a2a9faf0cd0942c7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "2d4ae88cced23229ba9984f3d94b2ca715bb0c980986acb34a99cfd8e078e18d"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "15470acb2f4e4efed6cc39ec7a19eed579871af0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "6b965d6781d924be2bcfa6edd9f7221bfb6356d6e0c5f074d655ba6b9bb56875"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9e82ca36990c18638a08ffb82ac1cf23d1eec36"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "a248580b5bec77260a3ff5e775bf83c09789cad1e89ac71becf81da584c8335a"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f739b2aad8ab1c3527490e1d8be43a7e653af9ee"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "bbbb83545cab2e694490d54c37aaa22a14b73580c3ff4d1ef9071789bfb534e2"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "136b050b92732e321a1b1b7914dbdd8e30a27ada"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "e712296481be3a78773420f325580d7c1fe836817f4ac360d589b96950782ac8"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "e2eafa6a835ef6d5633c35957158673682846c76"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "b17054776b2aa38a60cfd6b9b778654289cca051a82c09a7ec6f0c0cb9bff18f"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "d5713da94b313fbbf0c171bbf6ee5dd2df420711"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "ffb89b0628c267a62a1bf62166f9584881e5ae7ca664d7089653b7f549b9ad49"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "b0b86186db774d4f13842d1df3b09f103925a2b3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "1fec246924d7c88888773879a45b9059f556a4486d6517917a446aeda4dc6277"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "4cb54c225b599da64356ddb8426d7096e24ed8be"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "4c0b9fd1103999f6c7310d441a0c64da0f5dbfd6f1fc96150c5f2f9c95a59b63"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "341ffc556fc759d0f8317f1233fc1e547211f15c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "fe6ea3365ce164a590ecb5e7b8caddf7fc3103c235aeeedaa868896bc19e7da5"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "81940e08cbc18e4ed48ddd47edc32048a019eff4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "81e60086b6b4aac50c5c5060049ce5550993d7131475f6bc6c4c954182c3fb3f"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "f871ee2006d77f0dfcc6a1b67f5dce3b5c014c35"
libgfortran_version = "3.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "1cf6131bbbd01ab38b3c3f2fb8ce9b5e4db94d0b5ab7d8b6cf5ced4ad0865b69"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "35ee135f6016cf2ba9485d3847fb71bb8339afbf"
libgfortran_version = "4.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "03dc88a2f006674f92e81526f1de060eeae4eecd9acbb2976ce55a9ed05966ed"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "2e3a1fde53ab64d6e5f0dfbbe9b7547ec3611742"
libgfortran_version = "5.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "1d6797babfd83de379db5a1e0d75f528d5f2520f03b5d143e6a2e62c722644de"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "93dd205cc3562f49968a358ca497b355417947a9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "f9b28b60255aa68c0df8745c4b5b55178d5883e01fcc0f55729163a59024b7d3"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "33b76dbbabd7027eeb8864aac69041caf7c51ef5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "e8596caabf45809ab6abccb41ec0de5e9fcaff8275decb1c90c0c4c276ca0e4f"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "3d86f9e2559c4a6cbe73143bff335f9216f78b6b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "faf34b19f25d9cb8d93292a9d9246bd20340c26e76e1e61ea3689f8318521121"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "5a822bd193ecf234c90d948320809a239bfc71db"
libgfortran_version = "3.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "572f10ea9dd82dc2fd341db0963a1873b84c42ba0d41529855fe12ee69fe5404"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "15a817689235506faea2a7b05cf766f525fca5ee"
libgfortran_version = "4.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "e7b1a3490f2845c8ee88d0b6b1c595ed11f2fe877a3489709e04d2a5aa1a3bab"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "4c13f236b0f2dbc42e34e2f5e1be7f1c192b4b1c"
libgfortran_version = "5.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "664117b3ad11296313d1aaece1632eae9fb67462264f1edb62caab4e0b3ffd88"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "94ffbbd7b1d0cc8155b3d173d7ecea6e0ebf6216"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "29e808fda0261f1992f03f5ba25df912ad274a028acfd9743a0638c43963b948"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "75f692fd7d7f0e4b629d0716015adde749f593ba"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "26412e659b98a66619539fa94fca522b670b69df79fe3a0f0a0adcb6cdfbd794"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "60195113c959749d27ba9758431724fd75394482"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "5676f226be4d1ddd0eeb8a1380bc4f9b06509184b16fe796586dd116608d2de2"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "bb519b05171279314af1f050a62226396b20a3e5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "f3e1c3c14b620194aef0158ad6038fe34da854890b56f3b08e5d35ea1b4ee680"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "944b0dff6e8587a61c7ff69a1b9bc1139ecc8f02"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "8d9c98b237e2fc383af3aaf5581d13eca2d982f5da3c2bde0fb2c3f9af6947cd"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "5d73f331660036dc669cfbb736265db8763411d0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "f9d16def8ec62307716f33271ec52e1b870ab280c77016d8c75dabecb3bcd3c2"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "cd5f2ce24ee9ef741d62bdc30177357839bcd666"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "582637128eda3d1788419c3f5fd56f4e42e5735c8d51bd0d0beba9e69a6b0e22"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "c82dd8f41f2f5c117368d36d5a03ecf0bca0fd96"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "fa0f1d0de7ab87525c9a9f3e2d6013d76db35f595ba43fdc01410e38332eb13a"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "6563898d2bd6fc9599695380131370ad6564d086"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "2743a6ee22d34050a219e6bf759ca2b09a6bbddd930e484003cfc1eb7b961a3e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "f39a1f608f87a7385735eca068365e4e7e271f2c"
libgfortran_version = "3.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "3c0027b910cf9a0fd0cebf0fb6186bfa401384e2577194add511b05423315fbf"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "c8ed1f7e41d834eabe64fc1b73cb55bf2ff50865"
libgfortran_version = "4.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "1227cc4272ad238fe3ded11989a4ec87aac6deba4fb19a7f64680bf0a8dbcf2c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "6992eba2388be5fc15cd0d038cd72aa444de0879"
libgfortran_version = "5.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "2a7d1cb088d879af3707c978d684d34bbb32eae00c294100f8dcfc51e088aee4"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
