[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "503f84387823e1939dac6e707ac0bd7d26f424f6"
libgfortran_version = "5.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "8fdb1f8ac98d2266a0d99072195f7ec118c0ec9e324068a3b6315057bdfc240e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "cfcc948149754dbe7642f154739602e7968b1eb7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "ec7babc8b4d8b71f1e00039717bd768f0e076d76d45caa733837b6afb1f2d6bc"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "db9f46c10103d415f77be5d1202dce29c9cac621"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "187bd7b7192b97250eecc6d9de452b688bead129c17443a1618ee5166d43b391"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "000a46409cafcb4a06f29b7d992da42ca30a7306"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "c9e333bbc4d85ecf901529f6ad95bd9eb0047179603c1960642663f826960ad3"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "147cce2b4889ab732f18b444cc9d270326e2c091"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "55ec5a11cfd9f98475ebd344b750c3cdd550e154dd4e003ee3a8f031c04cfb41"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "318e2aeb2739990cdd9b1fd16bdaf545f1583376"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "db1decca3ae1310fcf4e60174f8141b70d700c49c588fd3b3233b9b7cb8c031a"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "0c3f688a6add72d7a75195f0d2b85930e8876ca9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "e5fd41b23d32f6ccb8d1b40086e04bea538762d0cfe4683b2c6844831325f79b"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3036990f610d73c3644d1a5257045812c5d98d14"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "b37dd19f90fc16d29edf112b6f6d3cf347473dc6f14e2cffa5e42ed822903e70"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dad8d0b3bd7dde90d236fd9b38c5be412818b8f0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "c07f800442953e5703dac2edaaa70b1ce226837bdd6355c1ba5f17561a9749b4"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ebfab15c453f68ac743ad8d6b837f7007afa9698"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "418a9fe340a5e80ad12b96330c413be2d81ce547869a5359890eba4e46738293"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "be521073d8edb5b40d3c1d0cae222502d3fc6a61"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "9afc5b835a64c41bf1f942b3c97529482aad5b56882e51951861b947ac8959cc"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bc2a42de976f3f56a3c53a532e683b3494667754"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "0b6168fee1880fac5e903303fdf1cedede26635a5a442f9a609bc3ae560d3597"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "544eec91d156497ec4aeccaea9683baa8632490d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "70a188903380552fd163ff63587cc046cca7a7b3f8947b9e3ff72f746c6889d1"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c50394746b0d20716ccc920ace337fa38e81738"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "ed207e60a9b2754f189d225c249d8eaa19ad53b6f53d57318a0c40c00e63d33e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "557ebf5758dd0719c272071282e2c661acc7602e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "2e2b51e7dd01bd0433847e7657583c58dff819fc90e57454ca87bac2fa6806db"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0c4d6374ff5c5df258d7f50343d1a9a1b99448ae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "431b453ff3d467b6f1a61d4014ef0beaccc85eb0bce89fae93fad389dba5361c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aebc338a8f21753deb2b4f37cdc8964e55f04e25"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "495b81eeba4102c4288eec3b33d1d159f2fe64f79a647afe2d4cf31ebcae9548"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2a955b8059b89c657d826e1466a0767c8006f2ff"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "54ccfe11f9d7231e0a6c38f1799b6fde8028942d4d96d93e60852890822e8375"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e52cd12c7c6d14e233fa0ed218eafcee817b461b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "b642504154b93d41ac38af701eb51b812b733ecb94157ac13e9152707748b603"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "7241007c5800a21145e64956088a79b7131edc40"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "5161319ccb289cb21dd2eee8b7e6521b7a32e74ab54a3817dbb23a30f5d0fe2e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "d40a842f5908cf353e2460bf1079a0fb4d2d5ab6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "ed1eb4ec19d1362445cb6a25bef4cb48b5b0f2fc4c17869f62cb2c976304e006"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "5e90ff47e471aaaec843bb5fb15a95d1fed2afba"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "30ef766a9eb66207dd7f00737a636b4af88d0377ed0e6adfb95c51234999b0ed"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "40641f94908c66e75d1f781b789d5099977c2f2f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "d6528c962178122a0dedfb03ef20574b9201cf28b5aa95897fead2f349cb4290"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "992fb869a498558adc50375e5bf6c4b0543f2288"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "5b710f21fc94c9ed43f2e274e42882c908ec448591579a3279b66e4a78951a30"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "6942bf6d7771cc1b02999b2bb67d283373b23939"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "c90fa88380b868aba51e058d7fc6a50500f7c178c381cb4c0608998d47082c6f"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "ade1c7377e30cec4d80533336b4a749e2f7ac136"
libgfortran_version = "3.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "dfeadd9718657ecb858bd7fce9952521815a33f8183de2cd9961b4e3d1e711d7"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "47c1cc9476a58a8953e079e61357cd11c55adf71"
libgfortran_version = "4.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "7090f35c4d295a0045b1c241d36d9101e9fa3bcafa11268be18086c367f7c073"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "77d9194fae3639d1e2ecbb82267b8b1867cd4b2a"
libgfortran_version = "5.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "039ce3153defd9450226b1618d63e7d0bc2df707bbf8f807a74a23feca63210e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "57974ca88a51770438a99769ffc2202a7331ccbf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "e01f12ada56409a4581ab6b7c0f6313c1c3fe40976db204ebcaddbe4c87389d7"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "4839835ead4a1b383c60e42bd98b5c7e0d7cb6ce"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "a8822d34bb44de9e90eecc6f28d7a8cc0a644d40443aae78804722d0d4eff14a"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "e9cb0d4565340fbbc373462b24419fdd5b503532"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "9597c3aeb60d83424d6dbd781c94e912624adcabf6a637693fc9238e3ac3e433"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "bdaf15a1c84049114122dd9f9b015b232cd06f9d"
libgfortran_version = "3.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "40417d01d67e4c16557c2e0760c3e1efa197e55dbcd583fbaafd16bac2a35ec2"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "82e9c61da4ceeb7877ba0ab3b0230c1517e6c3cb"
libgfortran_version = "4.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "6a72173c9cc07108daeceb4ac4f83523648f6079fae6b87da8865aac9428a9da"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "87a028cbb7677eccc9af7932cced785232c3259a"
libgfortran_version = "5.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "69318a013c5216b9fe7653c3d65627877280f3e1680237fd2f7a3e1d465c739b"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "f37b94074ab3c7a06671da37ed2d77c176cfce42"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "12b6699e41bb506af61bbd9124ff905f1765a08b02d85d2dc2986624600d4466"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "cf36e0f4822fc2e94ed260b077b8f185d9e4ebd6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "fa053ab6339c1b89b5cfc0470c75c0832bc4f9c6fb02721a774f66b50d74548f"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "12f2530ed65eb689637e71283cbe1eeb31e2bddb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "0e543e720d5d19724454a889acc76cf8abf3fc6b8d3171939aa218d0ddf6579e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "87add40091ded3653cab2556f88f7202ec152f66"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "c93afd80d9ce812a9d598a682ffdcc9d395763c6c1619614112dc15fd7558386"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "5d097242581b9003508a9dfdc259e64c5dbb15cb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "04df3e216df2f12587eab373fada3a4510c1ea356be611f0ef31079082520899"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "c53eb50a0885239fb74b823484ec3e010fe605f2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "2875446079840e0c4620669952a5c5f6fedc09272f99e0bbc57d171a1e1fbf0c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "666e3a824f48f80036a372fc62f6fa88ce8a7460"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "7931989efec4ae971182108fd4a0114d6ca589bf3640d921837e84e398900ad7"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "02a59398a39cf6326a8a30c6697f7bc0c20e56ff"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "88af14aba19822531f0c2ec58cb025fdc23d327a60042078a9946f487280f65e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "2eb88fe12d4daa354433a32aa7360a4da2c344c5"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "66faa4dc965985a4eac4f406199e5cb2bc81db095b4d3d74f836668d3c561b9d"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "81999781361137be00a380a29aaa4be3493958b4"
libgfortran_version = "3.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "bf3c7d9cdf4c70af80cde63e8fc305bd067a08c5848f0d73c571ac7f657fa70e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "a02fa28c17b246b69c9d5346a6d48d1cc3fe3b0b"
libgfortran_version = "4.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "4dcb2f5a90fb32fc66f1abd71c4d0c60891ce8bdc218db8da662fb3b995bd0de"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "9aa21184a3ce11183cca5e1cae091fae62b08215"
libgfortran_version = "5.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "064704ccdbb15d0a40773833f9b827b0a91f359bd19791ba8e0eab1776c4a9b2"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.1+0/SLICOT.v5.8.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
