[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "16527b352432750fa349a2fb7edeb03ea863a6b4"
libgfortran_version = "5.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "f2249e6f8ccf606ca2f5200187f0a9bfe3c5ff4110a1ec0830223e900b7a572b"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "980b0f22e44f69ee19ceb79afbbe973547fc2b3a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "280f96b9fc97ef0dc1261c5251e0ecb7b62ca8066b84ae650759bbf3eeee22db"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "cf98e0d8df32a07d990a731727374845170f548e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "0094d4be5a5d4c5c457b5307a62e9d590edc1aa1aff424f2353c4a4e9b8cf86e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "a574aa15d3d8774ba36de10e350eb8fcc8abc260"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "7e0f6ca0ffaea57e161bb0c875a93d303b49d7a8bfd79c02d42729a9a9081377"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "dcd3f14c89368d38d41736e1d03c87d837da38e5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "f888cd93b5bb150ccfb1f7dfdd72084c6d46e2c23d6860b45c8860969453b91b"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "f02c0c7e67f9b7c2ce311bbbef0575a522e8089e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "e61e90344a0072e2058ec4588f4f8e370146250d1f5aa66ac954575ca9dd6edd"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "aarch64"
git-tree-sha1 = "42f760a125ef6d5bb58d404eef74318a921edc4a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "633fcbff5be3eb8544f200eda55d99c8112606dc73f73d578d57d9bed13b81f4"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ef95b35c01b92a2aa7ce855c7c89c52ec892abf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "b28d9d1b88a7509feed19138e4d88e2c98173d753b1ece8b5ebd0e08a2f36880"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9ec0fe1ec06710c1c8dd7b1f7904b7576b0ce9d7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "0382a5afff38be76544596ffc2cb645500c146d13385109b9257962c44a60d71"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "44ade766e529b21f8974169bf2e056eff35c3d58"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "bafb48e9dfda91f7ca379696c94f4ba8435b2140912f69939b5934b7ac913535"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f89fac83b13b061c9e1dbc829a3b52b1666e3cbd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "b345ee8e355fe8f9cffcd8873a654aa0c84e318ffcddefa94fd274a60dcfa420"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eb5a38a6d3afdb7cdf0d6ec5a4a58e9f9504a6dc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "047bcfd10111144dbd8e8d28be5558066951aa494cd2bccd01594acd8484dccd"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8713152ae3b309045208fe30f43c777cf0152032"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "621d5b2cc260ee3a29535c0f2cb018e77d6329320728ee1e88f613d2d2dcf188"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0dad3863f4834f3f8fa93a4e4e5db147a9afd0ed"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "42dee594307d395febf53b3ed7e7fd637b586df62c69a088fa0e07e340e06d60"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "693ddcff685545885fbffc5fcec0c54428c07d31"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "940d14121b5886358a187539e0cc44f47d39fff672645a347f93f854fae0cf3c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "21a10e1a8fd3e81564cc51816f1e1c5327bdba5a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "315699c12f5a358cf2ec707c88207c6a9fbf585581967f463519f7fbb4a32619"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "84e13b4dbece6bf26ef255ca23f1e14c898a2ab4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "dad65d6700cc7838527ea9441d7e573c279d861c661a2426ccd0ca8ba5aca04a"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "52d36f7a0296aedbb733ca510ad73657c16ad343"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "75e7e36a33975ee65259fc9fbb043180492782a89db97fe11eed5740f40d3dd7"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SLICOT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d62c33636370bbdb2962a95fde7757f79395b0d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "66aafaa979f12f577c170283ffb81978bc2c18ecf49147891adbd7af78d6fec3"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "7074f5733d9631ba0ae6643467074de00c60a143"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "63fc83be95269f35fdcc0fd11391ebf4bb6929d392adf37aecdda0449fad4d49"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "9a25f4c95ec8fba50c43d65018bbf406f981caaa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "ec5b115d96c8a52a4235f8ee7c9f7102c655beab7350b02fc6afabebe5886fbd"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "13a88e27c2d241a64ebc36bfbe12f46d26a25992"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "32a8e0fc98ff23d22300bdf94a4bd9f6844b0dfc533f7756a57067c9ca35d35e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "2e04164a238d61087991c88ccb697c7a46cca726"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "8d3a0b550b7e869a185f6584b5db7ec3120eb577efbd123f4c15fc691c7f4913"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "918e3bb5e040e64cad7954fff14ac7192a3da96b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "baf4680af2edfce1925b21c12236ab5b40a2cb1854364890cfba0560c98f7f3b"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "f32c65829adcc3d6db0c8326164413dea4863ab0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "5ec34c1e56e24020873857097c3efc7ef54ff8186f90038b8ce98c58df70aac5"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "85eef1af1e26b2c41321755faa970c2edea89886"
libgfortran_version = "3.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "bb000e3b1b32f8823797f79a1d9e7126b38cd1db2f12ca20033c7332c988f5bd"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "e94a792974d7c6082528b7e29ce8e6c1939d9ced"
libgfortran_version = "4.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "773f3300d2ca7d62ca4baffbfe7816fa611d7e0ad738c9567fea7d62dbc8528b"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[SLICOT]]
arch = "i686"
git-tree-sha1 = "0991cf314f1ae5ad2687a695aa949128a9cf2ed2"
libgfortran_version = "5.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "9dcff1a249fb37d219dc9a92cae18be61df7f5a5d2132bd3e8e5274ac38a4acf"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "1de877a357e367c7325f80c78a4b544bd278ba7c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "80d37bb21ed8c16ac26c71b7acae933a3f7d1c34b1704e8a8618eb3384b980ca"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "841fb3e4a4c0b0472d7d62a6373cece0619154e7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "f26d4ff50fc0433c8b020f625385239b5d7003a0220b7054fec49174bda06111"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "powerpc64le"
git-tree-sha1 = "b4a771108d135cefcd6fcba581d24235e7a299e9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "2f5c9973cad54c4dabd0234c4ad30962b6058ad53b30bf2283734e96fbbd610c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "ee659b3c3ffcf4660199266049b6614c251ee6a1"
libgfortran_version = "3.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "f92329b9dfc927879c1ef130bcf3ad7ea1b08955297d599b68fb61855b2a2f17"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "a1eb497ca4ed6af6782e40967fec8aff2496da8c"
libgfortran_version = "4.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "8003457c3893c1a33df609dcce0cc8dcb35be5e46fcc387377b5ae8a7718cff3"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "aa304f66a4e576dcac444796a9f5d8adefa06ca0"
libgfortran_version = "5.0.0"
os = "macos"

    [[SLICOT.download]]
    sha256 = "3ef1ff04edd494301f445a622615f2d192b85f723a2f6388f53a8b22e2fa1aa4"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "16962176c766905daa42470e4ef728491709ae0c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "dc9ecda45f75b012350512f1394f27d97c3d2fa97444364105d62103039b901e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "2bc34ec13d8c6a8341245c5924ae0aa9b473d01d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "e8a706baad51e551db672694c14c2871a425c8301ebd695ac5ec008aefc9f120"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "2d5be669284e9a58037d5521f08e33b2c0b29669"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "c114663c171f05c37a64d3eac0f146b4dce6364711064dfe16167f28e96873fa"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "e726f6231009acc80b77ccbecb29ae9ddedbf0ec"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "79ed6fe2f154ddffaa265bd79892dde8cb2c0104d68ffb036a176f317239500a"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "d97bc23d44f7d362de0abeb3da74d9ba3662d99b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "8776c004c7b9982049de2e75ee4ffe2a4dfb341b3897b5155e8c8e7cf2f49e8b"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "d77cb8b034b03bc0dc059eb3182ba5d16bda8c2f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLICOT.download]]
    sha256 = "253a309a58ceceab04bef2bdab18538f01957761f559fa7db7273f8073b13fa4"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "6877513a1b0048b5af68ffc56ebc05911303a8e6"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "974b92b86f13231b6772740cb53d02f4f353b314b33af1fd6326932ddc224b4e"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "71eb41130171d8e3e1b8957d652e6e242362165e"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "0f96c6f83849c642ca81705dd540c4335656d42aee02d249783ed2f4fc9dcd4f"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "5f09bcdbc43f501dcf418e6b9a200c095438bb1b"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SLICOT.download]]
    sha256 = "a1644773e3afa207f1150b56c0b5eac98de42f5581b8984c0942dfbc6cda8afd"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "0464f41169a51d819aad00b07bccdff5aaaa9c30"
libgfortran_version = "3.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "033a4cd3154816e8e4b7294507ce0a28c64b9d0d4cee68e7e675fcf46d45c53c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "a3013d89d691f28a5596d3c02a3cb2a7a14410c4"
libgfortran_version = "4.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "db93b3f67c7d837efb3f4199857b63b4cc557330b6850f5ae9cfa71af7b2a59c"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SLICOT]]
arch = "x86_64"
git-tree-sha1 = "836ea03039f6c32a84869b3eac88ecf8dca66422"
libgfortran_version = "5.0.0"
os = "windows"

    [[SLICOT.download]]
    sha256 = "78a7b9aabc61f5a69bb58de0c83073c789e19785fbbe5757deed80b339475203"
    url = "https://github.com/JuliaBinaryWrappers/SLICOT_jll.jl/releases/download/SLICOT-v5.8.0+0/SLICOT.v5.8.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
